[package]
name = "aurum_memory"
version = "0.0.0"
edition = "2021"

[dependencies.bitflags]
version = "^1.3.2"

[dependencies.scopeguard]
default-features = false
version = "^1.1.0"

[dependencies.unsafe_ref_cell]
path = "../unsafe_ref_cell"

[dev-dependencies.proptest]
version = "^1.0.0"
